app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from web.views import auth_view

admin.site.site_title = 'LEAN! 管理サイト'
admin.site.site_header = 'LEAN! 管理サイト'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/social/login/cancelled/', auth_view.canceled, name="socialaccount_login_cancelled"),
    path('accounts/social/login/error/', auth_view.error, name="error"),
    path('accounts/', include('allauth.urls')),
    path('', include("web.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from allauth.account.views import LogoutView
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from web.views import index_view, misc_view, auth_view, profile_view, account_view, auth_instagram_view, \
    auth_twitter_view, auth_youtube_view

app_name = 'web'
urlpatterns = [
    path('', index_view.index, name="index"),
    path('api/users', index_view.more_users, name="more_users"),

    # auth
    path('login/', auth_view.login, name="login"),
    path('signup/', auth_view.signup, name="signup"),
    path('leave/', auth_view.leave, name="leave"),
    path('thanks/', auth_view.thanks, name="thanks"),
    path('invite/<str:parent_id>/', auth_view.invite, name="invite"),
    path('logout/', LogoutView.as_view(), name="logout"),

    # profile
    path('profile/edit/', profile_view.profile, name="profile"),
    path('profile/<int:account_id>/', profile_view.profile_long, name="profile_long"),
    path('profile/<int:account_id>/ig/', profile_view.profile_ig, name="profile_long_ig"),
    path('profile/<int:account_id>/insta/', profile_view.instagram_list, name="profile_long_insta"),
    path('profile/<int:account_id>/twitter/', profile_view.twitter_list, name="profile_long_twitter"),
    path('profile/<int:account_id>/youtube/', profile_view.youtube_list, name="profile_long_youtube"),
    path('profile/<int:account_id>/yt/', profile_view.profile_yt, name="profile_long_yt"),

    # account
    path('account/', account_view.account, name="account"),

    # misc
    path('ask/', misc_view.ask, name="ask"),
    path('company/', misc_view.company, name="company"),
    path('manage/', misc_view.manage, name="manage"),
    path('tos/', misc_view.tos, name="tos"),
    path('policy/', misc_view.policy, name="policy"),
    path('about/', misc_view.about, name="about"),
    path('about_verification/', misc_view.about_verification, name="about_verification"),
    path('about_us_thanks/', misc_view.thanks_contact, name="thanks_contact"),
    path('articlelist/', misc_view.coming_soon, name="articlelist"),

    # oauth ig
    path('auth/ig/login/', auth_instagram_view.login, name="ig_login"),
    path('auth/ig/logout/', auth_instagram_view.logout, name="ig_logout"),
    path('auth/ig/login/callback/', auth_instagram_view.callback, name="ig_login_callback"),
    path('auth/ig/callback/', auth_instagram_view.callback, name="ig_callback"),

    # oauth tw
    path('auth/tw/login/', auth_twitter_view.login, name="tw_login"),
    path('auth/tw/logout/', auth_twitter_view.logout, name="tw_logout"),
    path('auth/tw/login/callback/', auth_twitter_view.callback, name="tw_login_callback"),

    # oauth yt
    path('auth/yt/login/', auth_youtube_view.login, name="yt_login"),
    path('auth/yt/logout/', auth_youtube_view.logout, name="yt_logout"),
    path('auth/yt/login/callback/', auth_youtube_view.callback, name="yt_login_callback"),
]

web/views/account_view.py
from django.shortcuts import render
from django.views.decorators.http import require_GET


@require_GET
def account(request):
    if request.user.is_authenticated:
        """アカウントメニュー: ログイン後"""
        return render(request, 'new_account.html')
    else:
        """アカウントメニュー: ログイン前"""
        return render(request, 'new_account2.html')

web/views/profile_view.py
import logging

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET

from web.forms import AccountForm
from web.models import Account, InstagramInfo, YoutubeInfo,SystemConfig
import requests
logger = logging.getLogger("main")


def profile(request):
    """プロフィール編集"""
    if not request.user.is_authenticated:
        return redirect("/")

    if request.user.is_staff:
        return redirect("/admin")

    try:
        account = request.user.account
    except:
        account = None

    if request.method == 'POST':
        # logger.info("profile:POST: request={}".format(request.POST))
        form = AccountForm(data=request.POST, files=request.FILES, instance=account)
        if form.is_valid():
            form.save()
            return redirect('/profile/{}/'.format(request.user.account.id))
        else:
            logger.warning("Error: {}".format(form.errors))
    else:
        if "form_data" in request.session:
            form = AccountForm(data=request.session["form_data"], instance=account)
            # logger.info("hasData: {}".format(request.session["form_data"]))
            del request.session['form_data']
        else:
            form = AccountForm(instance=account)

    return render(request, 'new_profile.html', {
        'form': form,
        "account": account
    })


def get_paginator(query_set):
    return Paginator(query_set, 11)


@require_GET
def profile_long(request, account_id):
    """プロフィールページ"""
    account = get_object_or_404(Account, pk=account_id)
    adsetting = SystemConfig.objects.filter().first().value
    if not account.user.is_active:
        raise Http404

    if account.is_private:
        return render(request, 'new_profile_long.html', {
            "account": account
        })

    # instagram
    ig_paginator = get_paginator(
        InstagramInfo.objects.filter(user=account.user).order_by("-publish_at"))
    instagram_list = ig_paginator.get_page(1)

    # youtube
    yt_paginator = get_paginator(
        YoutubeInfo.objects.filter(user=account.user).order_by("-publish_at"))
    youtube_list = yt_paginator.get_page(1)

    # twitter
    twitter_token = account.twitter_token
    twitter_id = twitter_token.twitter_name if twitter_token is not None else None

    logger.info("instagram_list={}, youtube_list={}".format(instagram_list.has_next(), youtube_list.has_next()))

    params = {
        "account": account,
        "instagram_list": instagram_list,
        "youtube_list": youtube_list,
        "twitter_id": twitter_id,
        "googleadd" : adsetting
    }
    if account.ssp_landscape is not None:
        params["SSP_TAG_LAND"] = account.ssp_landscape
    if account.ssp_post is not None:
        params["SSP_TAG_POST"] = account.ssp_post
    return render(request, 'new_profile_long.html', params)


@require_GET
def instagram_list(request, account_id):
    """プロフィールページ"""
    account = get_object_or_404(Account, pk=account_id)

    if not account.user.is_active:
        raise Http404

    if account.is_private and account_id != request.user.account.id:
        return render(request, 'new_profile_long.html', {
            "account": account
        })

    # instagram

    query = InstagramInfo.objects.filter(user=account.user).order_by("-publish_at")
    page = request.GET.get('page', 1)
    paginator = Paginator(query, 6)
    try:
        numbers = paginator.page(page)
    except PageNotAnInteger:
        numbers = paginator.page(1)
    except EmptyPage:
        numbers = paginator.page(paginator.num_pages)
    # instagram_list = ig_paginator.get_page(1)
    params = {
        "account": account,
        "instagram_list": numbers,
    }
    if account.ssp_landscape is not None and not account.ssp_landscape == '':
        params["SSP_TAG_LAND"] = account.ssp_landscape
    elif account.ssp_landscape == '':
        account.ssp_landscape = None

    if account.ssp_post is not None and not account.ssp_post == '':
        params["SSP_TAG_POST"] = account.ssp_post
    elif account.ssp_post == '':
        account.ssp_post == None

    try:
        r =requests.get(params['instagram_list'][0].url + '?__a=1')
        instgram_user_id = r.json()['graphql']['shortcode_media']['owner']['username']
    except:
        instgram_user_id = None
    params['instgram_user_id'] = instgram_user_id
    return render(request, 'parts/new_instagram_list.html', params)


@require_GET
def twitter_list(request, account_id):
    """プロフィールページ"""
    account = get_object_or_404(Account, pk=account_id)

    if not account.user.is_active:
        raise Http404

    if account.is_private and account_id != request.user.account.id:
        return render(request, 'new_profile_long.html', {
            "account": account
        })


    # twitter
    twitter_token = account.twitter_token
    twitter_id = twitter_token.twitter_name if twitter_token is not None else None

    # logger.info("instagram_list={}, youtube_list={}".format(instagram_list.has_next(), youtube_list.has_next()))

    params = {
        "account": account,
        "twitter_id": twitter_id,
    }
    if account.ssp_landscape is not None and not account.ssp_landscape == '':
        params["SSP_TAG_LAND"] = account.ssp_landscape
    elif account.ssp_landscape == '':
        account.ssp_landscape = None

    if account.ssp_post is not None and not account.ssp_post == '':
        params["SSP_TAG_POST"] = account.ssp_post
    elif account.ssp_post == '':
        account.ssp_post == None
    return render(request, 'parts/twitter_page.html', params)

@require_GET
def youtube_list(request, account_id):
    """プロフィールページ"""
    account = get_object_or_404(Account, pk=account_id)

    if not account.user.is_active:
        raise Http404

    if account.is_private and account_id != request.user.account.id:
        return render(request, 'new_profile_long.html', {
            "account": account
        })

    # youtube
    query = YoutubeInfo.objects.filter(user=account.user).order_by("-publish_at")

    page = request.GET.get('page', 1)
    paginator = Paginator(query, 6)
    try:
        numbers = paginator.page(page)
    except PageNotAnInteger:
        numbers = paginator.page(1)
    except EmptyPage:
        numbers = paginator.page(paginator.num_pages)

    params = {
        "account": account,
        "youtube_list": numbers,
    }
    if account.ssp_landscape is not None and not account.ssp_landscape == '':
        params["SSP_TAG_LAND"] = account.ssp_landscape
    elif account.ssp_landscape == '':
        account.ssp_landscape = None

    if account.ssp_post is not None and not account.ssp_post == '':
        params["SSP_TAG_POST"] = account.ssp_post
    elif account.ssp_post == '':
        account.ssp_post == None
    try:
        youtube_channel_id = params['youtube_list'][0].chanel_id
    except:
        youtube_channel_id = None

    params['youtube_channel'] = youtube_channel_id
    return render(request, 'parts/new_youtube_list.html', params)


@require_GET
def profile_ig(request, account_id):
    """ Instagramのmore """
    account = get_object_or_404(Account, pk=account_id)

    if account.is_private or not account.user.is_active or "last_id" not in request.GET:
        raise Http404

    last_id = request.GET.get("last_id")
    last_item = get_object_or_404(InstagramInfo, pk=last_id)

    # instagram
    query = InstagramInfo.objects.filter(user=account.user, publish_at__lt=last_item.publish_at).order_by("-publish_at")
    ig_paginator = get_paginator(query)
    instagram_list = ig_paginator.get_page(1)

    # set parameter
    params = {
        "account": account,
        "instagram_list": instagram_list,
    }
    if account.ssp_landscape is not None:
        params["SSP_TAG_LAND"] = account.ssp_landscape
    if account.ssp_post is not None:
        params["SSP_TAG_POST"] = account.ssp_post
    return render(request, 'parts/new_instagram_list.html', params)


@require_GET
def profile_yt(request, account_id):
    """ YouTubeのmore """
    account = get_object_or_404(Account, pk=account_id)

    if account.is_private or not account.user.is_active or "last_id" not in request.GET:
        raise Http404

    last_id = request.GET.get("last_id")
    last_item = get_object_or_404(YoutubeInfo, pk=last_id)

    # youtubes
    query = YoutubeInfo.objects.filter(user=account.user, publish_at__lt=last_item.publish_at).order_by("-publish_at")
    paginator = get_paginator(query)
    item_list = paginator.get_page(1)
    logger.debug("item_list={}".format(query.count()))

    # set parameter
    params = {
        "account": account,
        "youtube_list": item_list,
    }
    if account.ssp_landscape is not None:
        params["SSP_TAG_LAND"] = account.ssp_landscape
    if account.ssp_post is not None:
        params["SSP_TAG_POST"] = account.ssp_post
    return render(request, 'parts/youtube_list.html', params)

web/templates/new_account2.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>アカウント（設定その他）│LEAN!─SNSを使っている方、インフルエンサー・タレント必見。あなたのオフィシャルプロフィールが作れるシステムです</title>
    <meta name="description" content="LEAN!はSNSを使っている方のオフィシャルプロフィールを１分登録にて作成できる無料サービスです。SNSを使うすべての人に。">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:type" content="website" />
    <meta property="og:title" content="LEAN!アカウント（設定その他）" />
    <meta property="og:description" content="LEAN!はSNSを使っている方のオフィシャルプロフィールを１分登録にて作成できる無料サービスです。SNSを使うすべての人に。" />
    <meta property="og:image" content="https://leanjapan.jp/i/images/ogp.png">
    <meta property="og:image:alt" content="LEAN!ogp">
    <meta property="og:url" content="https://leanjapan.jp/i/signup.html" />
    <meta property="og:site_name" content="LEAN!" />
    <!-- facebook -->
    <meta property="article:author" content="https://www.facebook.com/leanjapan/">
    <meta property="fb:app_id" content="680771545664378" />
    <meta property="fb:admins" content="680771545664378" />
    <!-- twitter card -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@japan_lean" />
    <meta name="twitter:url" content="https://leanjapan.jp/i/signup.html" />
    <meta name="twitter:title" content="LEAN!アカウント（設定その他）"/>
    <meta name="twitter:description" content="LEAN!はSNSを使っている方のオフィシャルプロフィールを１分登録にて作成できる無料サービスです。SNSを使うすべての人に。" />
    <meta name="twitter:image:src" content="https://leanjapan.jp/i/images/ogp.png" />
    <meta name="twitter:site" content="LEAN!" />
    <link rel="stylesheet" href="{% static 'new_static/css/site_structure_about.css' %}">
    <link rel="stylesheet" href="{% static 'new_static/css/site_content_about.css' %}">
    <link rel="stylesheet" href="{% static 'new_static/css/lightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'new_static/css/style_about.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'new_static/css/slick.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'new_static/css/slick-theme.css' %}" />

    <script src="{% static 'new_static/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'new_static/js/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'new_static/js/func_slick.js' %}"></script>

  </head>

  <body class="listtype">
    <div class="maxwidth">
      <div class="content">
        <div class="container_about laenpro-banner">
          <div class="box"></div>
          <div class="number-members">
            <div class="number-members-wrapp">
              <div class="text">
                        アカウント
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="text__bot">
                <ul>
                    <li>1.　<a href="{% url 'web:tos' %}">利用規約</a></li>
                    <li>2.　<a href="{% url 'web:policy' %}">プライバシーポリシー</a></li>
                    <li>3.　<a href="{% url 'web:company' %}">運営会社</a></li>
                    <li>4.　<a href="{% url 'web:ask' %}">お問い合わせ</a></li>
                </ul>
            </div>
        </div>
     </div>


        </div>
    </div>


        <script src="{% static 'new_static/js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'new_static/js/lightbox.min.js' %}"></script>
        <script src="{% static 'new_static/js/slick.min.js' %}"></script>
        <script src="{% static 'new_static/js/lightbox-video.js' %}"></script>
        <script src="{% static 'new_static/js/index.js' %}"></script>
</body>

</html>

web/templates/new_index.html
{% load static %}
<!DOCTYPE HTML>
<!--
Multiverse by HTML5 UP
html5up.net | @ajlkn
Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
	<title>LEAN!にようこそ│LEAN!─SNSを使っている方、インフルエンサー・タレント必見。あなたのオフィシャルプロフィールが作れるシステムです</title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="LEAN!はSNSを使っている方のオフィシャルプロフィールを１分登録にて作成できる無料サービスです。SNSを使うすべての人に。">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property="og:type" content="website" />
	<meta property="og:title" content="LEAN!" />
	<meta property="og:description" content="LEAN!はSNSを使っている方のオフィシャルプロフィールを１分登録にて作成できる無料サービスです。SNSを使うすべての人に。" />
	<meta property="og:image" content="https://lea-n.com/ogp.png">
	<meta property="og:image:alt" content="LEAN!ogp">
	<meta property="og:url" content="https://leanjapan.jp/i/signup.html" />
	<meta property="og:site_name" content="LEAN!" />
	<!-- facebook -->
	<meta property="article:author" content="https://www.facebook.com/leanjapan/">
	<meta property="fb:app_id" content="680771545664378" />
	<meta property="fb:admins" content="680771545664378" />
	<!-- twitter card -->
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="@japan_lean" />
	<meta name="twitter:url" content="https://leanjapan.jp/i/signup.html" />
	<meta name="twitter:title" content="LEAN!"/>
	<meta name="twitter:description" content="LEAN!はSNSを使っている方のオフィシャルプロフィールを１分登録にて作成できる無料サービスです。SNSを使うすべての人に。" />
	<meta name="twitter:image:src" content="https://lea-n.com/ogp.png" />
	<meta name="twitter:site" content="LEAN!" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{% static 'new_static/assets/css/main.css' %}" />
	<noscript><link rel="stylesheet" href="{% static 'new_static/assets/css/noscript.css' %}" /></noscript>

    <script src="{% static 'new_static/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'new_static/assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.min.js"></script>
</head>
<body class="is-preload">
    	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Header -->
		<header id="header">
			<h1><a href="/"><strong>LEAN!</strong></a></h1>
			<nav>
				<ul>
					<li><a href="#footer" class="icon solid fa-info-circle">About</a></li>
				</ul>
			</nav>
		</header>

		<!-- Main -->
		<div id="main" class="infinite-container">
            {% for account in first_users %}
                <article class="thumb infinite-item" >
                    {% if account.profile_image %}
                        <a href="/profile/{{ account.id }}" class="image" style="background-image: url('/media/{{ account.profile_image }}');">
                            <img src="/media/{{ account.profile_image }}" alt="" style="display:none">
                        </a>
                    {% elif account.profile_image1 %}
                        <a href="/profile/{{ account.id }}" class="image" style="background-image: url('/media/{{ account.profile_image1 }}');">
                            <img src="/media/{{ account.profile_image1 }}" alt="" style="display:none">
                        </a>
                    {% elif account.profile_image2 %}
                        <a href="/profile/{{ account.id }}" class="image" style="background-image: url('/media/{{ account.profile_image2 }}');">
                            <img src="/media/{{ account.profile_image2 }}" alt="" style="display:none">
                        </a>
                    {% elif account.profile_image3 %}
                        <a href="/profile/{{ account.id }}" class="image" style="background-image: url('/media/{{ account.profile_image3 }}');">
                            <img src="/media/{{ account.profile_image3 }}" alt="" style="display:none">
                        </a>
                    {% else %}
                        <a href="/profile/{{ account.id }}" class="image" style="background-image: url('{% static '/images/user.png' %}');">
                            <img src="{% static '/images/user.png' %}" alt="" style="display:none">
                        </a>
                    {% endif %}

                    <h2>{{ account.display_name }}</h2>
                    <p> </p>
                </article>
            {% endfor %}
		</div>

        {% if first_users.has_next %}
            <a class="infinite-more-link" href="?page={{ first_users.next_page_number }}">More</a>
        {% endif %}

          <script>
            var infinite = new Waypoint.Infinite({
              element: $('.infinite-container')[0]
            });
          </script>
		<!-- Footer -->
		<footer id="footer" class="panel">
			<div class="inner split">
				<div>
					<section>
						<div class="text">
							現在の登録
							<span class="count">{{ user_count }}</span>
							user
						</div>
                        <p>&nbsp;</p>
                        <div class="about">
                            <p> LEAN! - SNSを使っている方、インフルエンサー・タレント必見。あなたのオフィシャルプロフィールが作れるシステムです。
                                あなたのInstagram、Youtube、Twitter等を連携表示したオフィシャルプロフィールページを自動生成。
                                あなたのオフィシャルページが簡単ステップで作れちゃいます！</p>
                            <p><a href="{% url 'web:signup' %}">新規登録</a>　/　<a href="{% url 'web:login' %}">ログイン</a><br ></p>
                            <p>各種お問い合わせは以下のフォームよりお願い致します</p>
                        </div>
					</section>

	            </div>
	            <div>
		        <section>
			    <h2>お問い合わせ</h2>
			    <form method="post" action="{% url 'web:about_verification' %}">
                    {% csrf_token %}
                    <div class="fields">
                        <div class="field half">
                            <input type="text" name="ab_name" id="name" placeholder="お名前" required/>
                        </div>
                        <div class="field half">
                            <input type="email" name="ab_email" id="email" placeholder="Email" required/>
                        </div>
                        <div class="field">
                            <textarea name="ab_desc" id="message" rows="4" placeholder="お問い合わせ" required></textarea>
                        </div>
                    </div>
                    <ul class="actions">
                        <li><input type="submit" value="送る" class="primary" /></li>
                        <li><input type="reset" value="リセット" /></li>
                    </ul>
			    </form>
			    <p class="copyright">
				&copy; Unttled. Design: <a href="https://lea-n.com/">LEAN!</a>.
			</p>
		    </section>
	        </div>
            </div>
        </footer>

    </div>
<!-- Scripts -->


<script src="{% static 'new_static/assets/js/browser.min.js' %}"></script>
<script src="{% static 'new_static/assets/js/breakpoints.min.js' %}"></script>
<script src="{% static 'new_static/assets/js/util.js'%}"></script>
<script src="{% static 'new_static/assets/js/main.js' %}"></script>

</body>
</html>

web/templates/not_login_footer.html
{% load static %}
<div class="menu">
            <div class="menu__tab">
                <div class="menu__wrap">
                    <div class="menu__item menu__tab1 ">
                        <a href="{% url 'web:profile_long_insta' account.id %}">
                            <img class="show" src="{% static 'new_static/images/ic_instagram.png' %}" alt="">
                            <img class="hide" src="{% static 'new_static/images/ic_instagram.png' %}" alt="">
                        </a>
                    </div>
                    <div class="menu__item menu__tab2 ">
                        <a href="{% url 'web:profile_long_twitter' account.id %}">
                            <img class="show" src="{% static 'new_static/images/ic_twitter.png' %}" alt="">
                            <img class="hide" src="{% static 'new_static/images/ic_twitter.png' %}" alt="">
                        </a>
                    </div>
                    <div class="menu__item menu__tabicon">
                        <a href="javascript:void(0)">
                            <img class="show" src="{% static 'new_static/images/ic_main.png' %}" alt="">
                            <img class="hide" src="{% static 'new_static/images/ic_main_active.png' %}" alt="">
                        </a>
                    </div>
                    <div class="menu__item menu__tab3">
                        <a href="{% url 'web:profile_long_youtube' account.id %}">
                            <img class="show" src="{% static 'new_static/images/ic_youtube.png' %}" alt="">
                            <img class="hide" src="{% static 'new_static/images/ic_youtube.png' %}" alt="">
                        </a>
                    </div>
                    <div class="menu__item menu__tab4 toggleMenu">
                        <a href="javascript:void(0)">
                            <img class="show__menu" src="{% static 'new_static/images/ic_01.png' %}" alt="">
                            <img class="hide__menu" src="{% static 'new_static/images/ic_01.png' %}" alt="">
                        </a>
                        <div class="sp">
                            <nav class="nav" style="display: none;">
                                <ul>
                                    <li><a href="{% url 'web:signup' %}">新規登録</a></li>
                                    <li><a href="{% url 'web:login' %}">ログイン</a></li>
                                    <li><a href="{% url 'web:account' %}">その他</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="pc">
                            <nav class="nav" style="display: none;">
                                <ul>
                                    <li><a href="{% url 'web:signup' %}">新規登録</a></li>
                                    <li><a href="{% url 'web:login' %}">ログイン</a></li>
                                    <li><a href="{% url 'web:account' %}">その他</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="share">
                <div class="overlay"></div>
                <div class="share__popup">
                    <div class="share__top row__cen_mid">
                        <div>Share</div>
                        <div>-</div>
                        <div>ログインしてシェアすると<br>Pointがもらえます</div>
                    </div>
                    <div class="share__btns">
                        <div class="share__login">
                            <a class="btn btn__leanpro" href="{% url 'web:login' %}"><span>ログイン</span></a>
                        </div>
                        <ul>
                <li>
                    <a target="_blank" rel="noopener"
                       {% if not request.user.is_authenticated %}
                       href="https://social-plugins.line.me/lineit/share?url={{ request|current_url|add:'?openExternalBrowser=1'|urlencode:'' }}"
                       {% else %}
                       href="https://social-plugins.line.me/lineit/share?url={{ request|current_url|add:'?id='|add:request.user.account.page_id|add:'&openExternalBrowser=1'|urlencode:'' }}"
                       {% endif %}
                    >
                        <img src="{% static '/images/line_img.png' %}" alt=""><span>LINE</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" rel="noopener"
                       {% if not request.user.is_authenticated %}
                       href="https://twitter.com/intent/tweet?text={{ request|current_url|urlencode:'' }}"
                       {% else %}
                       href="https://twitter.com/intent/tweet?text={{ request|current_url|add:'?id='|add:request.user.account.page_id|urlencode:'' }}"
                       {% endif %}
                    >
                        <img src="{% static '/images/twitter_img.png' %}" alt=""><span>Twitter</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" rel="noopener"
                       {% if not request.user.is_authenticated %}
                       href="https://www.facebook.com/share.php?u={{ request|current_url|urlencode:'' }}"
                       {% else %}
                       href="https://www.facebook.com/share.php?u={{ request|current_url|add:'?id='|add:request.user.account.page_id|urlencode:'' }}"
                       {% endif %}
                    >
                        <img src="{% static '/images/facebook_img.png' %}" alt="">
                        <span>Facebook</span>
                    </a>
                </li>
                <li>
                    <a class="copy" href="#ex1" rel="modal:open"
                       {% if not request.user.is_authenticated %}
                       data-clipboard-text="{{ request|current_url|add:'?openExternalBrowser=1' }}"
                       {% else %}
                       data-clipboard-text="{{ request|current_url|add:'?id='|add:request.user.account.page_id|add:'&openExternalBrowser=1' }}"
                       {% endif %}
                    >
                        <img src="{% static '/images/url_img.png' %}" alt=""><span>URLをコピー</span>
                    </a>
                </li>
            </ul>
                    </div>
                </div>
            </div>
        </div>